import { Injectable, InternalServerErrorException, Logger } from "@nestjs/common";
import { randomUUID } from "crypto";
import { createClient, SupabaseClient } from "@supabase/supabase-js";

/**
 * The single Supabase client the whole API shares.
 *
 * Replaces PrismaService. The important difference is the transport: Prisma
 * opened a Postgres connection to the pooler and spoke SQL, this speaks HTTPS
 * to PostgREST. That removes the connection pool, the query engine binary, the
 * `prisma generate` build step and the `prisma migrate deploy` deploy step —
 * which is what was failing with P3005 against an already-populated database.
 *
 * The secret key is used, not the publishable one: this process is the trusted
 * server, it is not reachable from the internet directly (Caddy fronts it), and
 * it must be able to read admin_users and every application row regardless of
 * row-level security. Never let this key reach the browser.
 */
@Injectable()
export class SupabaseService {
  private readonly logger = new Logger(SupabaseService.name);
  readonly client: SupabaseClient;

  constructor() {
    const url = process.env.SUPABASE_URL?.trim();
    // SUPABASE_SECRET_KEY is the current name; SUPABASE_SERVICE_ROLE_KEY is the
    // older one and is still what some dashboards show. Accept either.
    const key = (
      process.env.SUPABASE_SECRET_KEY ?? process.env.SUPABASE_SERVICE_ROLE_KEY
    )?.trim();

    if (!url) {
      throw new Error(
        "SUPABASE_URL is not set. Copy it from Supabase -> Project Settings -> " +
          "API (e.g. https://xxxx.supabase.co) into the environment before starting the API."
      );
    }
    if (!key) {
      throw new Error(
        "SUPABASE_SECRET_KEY is not set. Copy the secret (service_role) key from " +
          "Supabase -> Project Settings -> API. It bypasses row-level security, so it " +
          "belongs only in the server environment — never in the frontend."
      );
    }

    this.client = createClient(url, key, {
      auth: {
        // No end-user sessions here; the API authenticates admins with its own
        // JWTs. Leaving these on makes the client try to persist and refresh a
        // session it will never have.
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    this.logger.log(`Supabase client ready for ${new URL(url).host}`);
  }

  /** Shorthand so services read like `this.db.from(TABLES.courses)`. */
  from(table: string) {
    return this.client.from(table);
  }
}

/**
 * Primary keys used to be cuids generated by the Prisma client — the columns
 * are plain TEXT with no database default, so something still has to produce
 * one. A UUID is a fine value for a TEXT column and sits happily alongside the
 * cuids already in the tables.
 */
export function newId(): string {
  return randomUUID();
}

/** `updatedAt` was Prisma's `@updatedAt`; nothing sets it in the database. */
export function nowIso(): string {
  return new Date().toISOString();
}

/**
 * Turns a PostgREST response into a value or an exception.
 *
 * supabase-js never throws — it returns `{ data, error }` — so an unchecked
 * call quietly yields `null` and the failure surfaces somewhere unrelated.
 * The error detail is logged server-side and deliberately not returned to the
 * client, which has no business seeing table or constraint names.
 */
export function unwrap<T>(
  result: { data: T | null; error: { message: string; code?: string } | null },
  context: string
): T {
  if (result.error) {
    new Logger("Supabase").error(
      `${context} failed: ${result.error.message}` +
        (result.error.code ? ` (${result.error.code})` : "")
    );
    throw new InternalServerErrorException("Database request failed");
  }
  return result.data as T;
}

/** Same, for `{ count }` responses from a head request. */
export function unwrapCount(
  result: { count: number | null; error: { message: string; code?: string } | null },
  context: string
): number {
  if (result.error) {
    new Logger("Supabase").error(`${context} failed: ${result.error.message}`);
    throw new InternalServerErrorException("Database request failed");
  }
  return result.count ?? 0;
}
