/**
 * Row shapes and enums for the Supabase (Postgres) tables.
 *
 * These used to be generated by `prisma generate` and imported from
 * @prisma/client. Prisma is gone — the backend talks to Supabase over PostgREST
 * now — so the types are declared by hand here instead.
 *
 * Two things to keep in mind when editing:
 *
 *   * Column names are camelCase in the database (they were created by Prisma,
 *     which quotes identifiers), while table names are snake_case. PostgREST
 *     matches on the exact spelling, so `isActive` is right and `is_active`
 *     silently returns nothing.
 *   * `id` and `updatedAt` have NO database default. Prisma filled them in
 *     client-side, so every insert here must supply both — see `newId()` and
 *     `nowIso()` in supabase.service.ts.
 */

export enum ApplicationStatus {
  PENDING = "PENDING",
  REVIEWING = "REVIEWING",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
}

export enum CourseLevel {
  BEGINNER = "BEGINNER",
  INTERMEDIATE = "INTERMEDIATE",
  ADVANCED = "ADVANCED",
  ALL_LEVELS = "ALL_LEVELS",
}

/** Table names, so a typo is a compile error rather than a 404 from PostgREST. */
export const TABLES = {
  courses: "courses",
  applications: "applications",
  adminUsers: "admin_users",
  teachers: "teachers",
  reviews: "reviews",
  siteContent: "site_content",
  pageViews: "page_views",
} as const;

export interface Course {
  id: string;
  slug: string;
  title: string;
  description: string;
  longDesc: string | null;
  duration: string;
  level: CourseLevel;
  price: number;
  isActive: boolean;
  isFeatured: boolean;
  order: number;
  tags: string[];
  createdAt: string;
  updatedAt: string;
}

export interface Application {
  id: string;
  name: string;
  email: string;
  phone: string | null;
  message: string | null;
  program: string;
  status: ApplicationStatus;
  isRead: boolean;
  readAt: string | null;
  createdAt: string;
  updatedAt: string;
  courseId: string | null;
}

export interface AdminUser {
  id: string;
  email: string;
  passwordHash: string;
  name: string;
  createdAt: string;
  updatedAt: string;
}

export interface Teacher {
  id: string;
  name: string;
  role: string;
  bio: string;
  tags: string[];
  initials: string;
  color: string;
  order: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Review {
  id: string;
  name: string;
  role: string;
  text: string;
  stars: number;
  course: string;
  initials: string;
  color: string;
  order: number;
  isPublished: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface SiteContent {
  id: string;
  aboutTitle: string;
  aboutBody: string;
  statStudents: number;
  statEmployed: number;
  statYears: number;
  contactEmail: string;
  contactPhone: string;
  contactAddress: string;
  updatedAt: string;
}

export interface PageView {
  id: string;
  path: string;
  locale: string | null;
  referrer: string | null;
  visitorId: string;
  createdAt: string;
}
